name: Build and Release

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: false

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      danielpigott: ${{ steps.version.outputs.danielpigott }}
      pilina: ${{ steps.version.outputs.pilina }}
    steps:
      - name: Fetch Release Versions
        id: version
        run: |
          echo "::set-output name=danielpigott::$( \
            curl -sL https://api.github.com/repos/danielpigott/cloudflare-cli/releases/latest \
            | jq -r '.tag_name')"
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "::set-output name=pilina::$( \
              curl -sL https://api.github.com/repos/pilina/cloudflare-cli/releases/latest \
              | jq -r '.tag_name')"
          else
            echo "::set-output name=pilina::${{ github.event.inputs.tag }}"
          fi
      - name: List Versions
        run: |
          echo "danielpigott: ${{ steps.version.outputs.danielpigott }}"
          echo "Pilina: ${{ steps.version.outputs.pilina }}"
  release:
    needs: version
    if: needs.version.outputs.danielpigott != needs.version.outputs.pilina
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.version.outputs.danielpigott }}
          release_name: Release ${{ needs.version.outputs.danielpigott }}
          body: |
            Updating to new cloudflare-cli release `${{ needs.version.outputs.danielpigott }}`
          draft: false
          prerelease: false
  build:
    needs: version
    if: needs.version.outputs.danielpigott != needs.version.outputs.pilina
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            pilina/cloudflare-cli:${{ needs.version.outputs.danielpigott }}
            pilina/cloudflare-cli:latest
          build-args: VERSION=${{ needs.version.outputs.danielpigott }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}